# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Team collaboration state + UDP LAN discovery.

Design notes:
- The 4-digit code is a *pairing* code (like a TV cast code), not a durable
  password: it only gates the join step, is rate-limited against guessing,
  and can be regenerated by the host at any time. Continued access uses
  per-member random tokens.
- Discovery: the joiner broadcasts ``{"df_team_discover": <code>}`` on UDP
  port ``DF_TEAM_DISCOVERY_PORT`` (default 15568); the host replies with its
  HTTP address only when the code matches, so the team stays invisible to
  wrong-code probes.
- State persists to ``DATA_FORMULATOR_HOME/team_state.json`` so hosting and
  membership survive app restarts. Member tokens live in that file — same
  on-disk trust level as workspace data; the host's LLM keys are NOT in it
  (they stay in the encrypted vault).
"""
from __future__ import annotations

import json
import logging
import os
import secrets
import socket
import threading
import time

logger = logging.getLogger(__name__)

DISCOVERY_PORT = int(os.environ.get("DF_TEAM_DISCOVERY_PORT", "15568"))

_JOIN_WINDOW_SECONDS = 60
_JOIN_MAX_ATTEMPTS = 5  # per source IP per window


def _data_home() -> str:
    return os.environ.get("DATA_FORMULATOR_HOME") or os.path.join(
        os.path.expanduser("~"), ".data_formulator"
    )


def _state_path() -> str:
    return os.path.join(_data_home(), "team_state.json")


class TeamService:
    """Singleton holding host/member state and the discovery responder."""

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._state: dict = {"mode": "off"}
        self._discovery_thread: threading.Thread | None = None
        self._discovery_socket: socket.socket | None = None
        self._join_attempts: dict[str, list[float]] = {}
        self._loaded = False

    # -- persistence -------------------------------------------------------

    def _load(self) -> None:
        if self._loaded:
            return
        self._loaded = True
        try:
            with open(_state_path(), encoding="utf-8") as f:
                stored = json.load(f)
            if isinstance(stored, dict) and stored.get("mode") in ("host", "member"):
                self._state = stored
                if stored["mode"] == "host":
                    self._start_discovery()
        except (FileNotFoundError, json.JSONDecodeError, OSError):
            pass

    def _save(self) -> None:
        try:
            os.makedirs(_data_home(), exist_ok=True)
            with open(_state_path(), "w", encoding="utf-8") as f:
                json.dump(self._state, f, ensure_ascii=False, indent=2)
        except OSError:
            logger.warning("Failed to persist team state", exc_info=True)

    # -- host lifecycle ----------------------------------------------------

    def start_hosting(self, team_name: str, host_identity: str, http_port: int,
                      shared_folder: str | None) -> dict:
        with self._lock:
            self._load()
            self._state = {
                "mode": "host",
                "team_name": team_name,
                "code": f"{secrets.randbelow(10000):04d}",
                "host_identity": host_identity,
                "http_port": int(http_port),
                "shared_folder": shared_folder or "",
                "shared_model_ids": [],
                "members": {},
            }
            self._save()
            self._start_discovery()
            return self.status()

    def stop(self) -> None:
        """Stop hosting or leave a team; resets to off."""
        with self._lock:
            self._load()
            self._state = {"mode": "off"}
            self._save()
            self._stop_discovery()

    def regenerate_code(self) -> str:
        with self._lock:
            self._load()
            if self._state.get("mode") != "host":
                raise ValueError("not hosting")
            code = f"{secrets.randbelow(10000):04d}"
            self._state["code"] = code
            self._save()
            return code

    def update_host_settings(self, shared_folder: str | None = None,
                             shared_model_ids: list[str] | None = None) -> None:
        with self._lock:
            self._load()
            if self._state.get("mode") != "host":
                raise ValueError("not hosting")
            if shared_folder is not None:
                self._state["shared_folder"] = shared_folder
            if shared_model_ids is not None:
                self._state["shared_model_ids"] = [str(m) for m in shared_model_ids]
            self._save()

    def kick_member(self, member_id: str) -> None:
        with self._lock:
            self._load()
            members = self._state.get("members", {})
            for token in list(members):
                if members[token].get("id") == member_id:
                    del members[token]
            self._save()

    # -- join (host side) --------------------------------------------------

    def try_join(self, code: str, member_name: str, source_ip: str) -> dict | None:
        """Validate a join attempt. Returns member record or None (bad code)."""
        with self._lock:
            self._load()
            if self._state.get("mode") != "host":
                return None
            now = time.monotonic()
            attempts = [t for t in self._join_attempts.get(source_ip, [])
                        if now - t < _JOIN_WINDOW_SECONDS]
            if len(attempts) >= _JOIN_MAX_ATTEMPTS:
                self._join_attempts[source_ip] = attempts
                raise PermissionError("too many attempts; wait a minute")
            if code != self._state.get("code"):
                attempts.append(now)
                self._join_attempts[source_ip] = attempts
                return None
            token = secrets.token_hex(16)
            member = {
                "id": secrets.token_hex(4),
                "name": (member_name or "member")[:48],
                "ip": source_ip,
                "joined_at": time.time(),
            }
            self._state.setdefault("members", {})[token] = member
            self._save()
            return {"token": token, **member,
                    "team_name": self._state.get("team_name", "")}

    def verify_token(self, token: str | None) -> dict | None:
        if not token:
            return None
        with self._lock:
            self._load()
            if self._state.get("mode") != "host":
                return None
            return self._state.get("members", {}).get(token)

    # -- member lifecycle (guest side) -------------------------------------

    def set_membership(self, host_url: str, team_name: str, member_token: str,
                       member_name: str) -> None:
        with self._lock:
            self._load()
            self._state = {
                "mode": "member",
                "host_url": host_url,
                "team_name": team_name,
                "member_token": member_token,
                "member_name": member_name,
            }
            self._save()

    # -- introspection -----------------------------------------------------

    def status(self) -> dict:
        with self._lock:
            self._load()
            s = dict(self._state)
            if s.get("mode") == "host":
                s["members"] = [
                    {"id": m.get("id"), "name": m.get("name"), "ip": m.get("ip"),
                     "joined_at": m.get("joined_at")}
                    for m in self._state.get("members", {}).values()
                ]
                s["lan_ips"] = _lan_addresses()
            if s.get("mode") == "member":
                s.pop("member_token", None)
            return s

    def raw(self) -> dict:
        with self._lock:
            self._load()
            return self._state

    # -- UDP discovery -----------------------------------------------------

    def _start_discovery(self) -> None:
        if self._discovery_thread and self._discovery_thread.is_alive():
            return
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            sock.bind(("", DISCOVERY_PORT))
            sock.settimeout(1.0)
        except OSError:
            logger.warning("Team discovery port %d unavailable", DISCOVERY_PORT)
            return
        self._discovery_socket = sock
        self._discovery_thread = threading.Thread(
            target=self._discovery_loop, args=(sock,), daemon=True
        )
        self._discovery_thread.start()

    def _stop_discovery(self) -> None:
        sock, self._discovery_socket = self._discovery_socket, None
        if sock:
            try:
                sock.close()
            except OSError:
                pass

    def _discovery_loop(self, sock: socket.socket) -> None:
        while self._discovery_socket is sock:
            try:
                data, addr = sock.recvfrom(512)
            except socket.timeout:
                continue
            except OSError:
                return
            try:
                msg = json.loads(data.decode("utf-8", errors="replace"))
            except (json.JSONDecodeError, UnicodeDecodeError):
                continue
            code = str(msg.get("df_team_discover", ""))
            with self._lock:
                hosting = self._state.get("mode") == "host"
                match = hosting and code == self._state.get("code")
                reply = {
                    "df_team_reply": {
                        "team_name": self._state.get("team_name", ""),
                        "port": self._state.get("http_port"),
                    }
                } if match else None
            if reply:
                try:
                    sock.sendto(json.dumps(reply).encode("utf-8"), addr)
                except OSError:
                    pass


def _lan_addresses() -> list[str]:
    """Best-effort list of this machine's LAN IPv4 addresses."""
    ips: list[str] = []
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.connect(("10.255.255.255", 1))
            ips.append(s.getsockname()[0])
    except OSError:
        pass
    try:
        for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET):
            ip = info[4][0]
            if ip not in ips and not ip.startswith("127."):
                ips.append(ip)
    except OSError:
        pass
    return ips


def discover_host(code: str, timeout: float = 2.5) -> dict | None:
    """Guest side: find the host of team *code* on the local network.

    Broadcasts on the discovery port and also probes localhost (so two
    instances on one machine can pair, e.g. for testing).
    Returns {"ip": ..., "port": ...} or None.
    """
    message = json.dumps({"df_team_discover": str(code)}).encode("utf-8")
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        sock.settimeout(0.4)
        deadline = time.monotonic() + timeout
        targets = [("255.255.255.255", DISCOVERY_PORT), ("127.0.0.1", DISCOVERY_PORT)]
        while time.monotonic() < deadline:
            for target in targets:
                try:
                    sock.sendto(message, target)
                except OSError:
                    continue
            try:
                data, addr = sock.recvfrom(512)
                reply = json.loads(data.decode("utf-8", errors="replace"))
                info = reply.get("df_team_reply")
                if info and info.get("port"):
                    return {"ip": addr[0], "port": int(info["port"]),
                            "team_name": info.get("team_name", "")}
            except (socket.timeout, json.JSONDecodeError, UnicodeDecodeError, OSError):
                continue
    return None


team_service = TeamService()
